Update theme_encoder.dart
peiffer-innovations/json_theme pull request #212
Opened 2024-08-18 17:05 UTC by Aysindb

Flutter 3.24.0 fix AutovalidateMode compile error

2024-08-21 11:36 UTC, TheRealNudelholz requested changes

2024-08-21 11:36 UTC, TheRealNudelholz commented on json_theme/lib/src/codec/theme_encoder.dart
> -      }
insert following case:
case AutovalidateMode.onUnfocus:
          result = 'onUnfocus';
          break;

2024-08-22 11:58 UTC, Aysindb commented
AutovalidateMode.onUnfocus.name return ' onUnfocus'

On Wed, 21 Aug 2024, 15:06 TheRealNudelholz, ***@***.***>
wrote:

> ***@***.**** requested changes on this pull request.
> ------------------------------
>
> In json_theme/lib/src/codec/theme_encoder.dart
> <https://github.com/peiffer-innovations/json_theme/pull/212#discussion_r1724899713>
> :
>
> >      String? result;
>
>      if (value != null) {
> -      switch (value) {
> -        case AutovalidateMode.always:
> -          result = 'always';
> -          break;
> -
> -        case AutovalidateMode.disabled:
> -          result = 'disabled';
> -          break;
> -
> -        case AutovalidateMode.onUserInteraction:
> -          result = 'onUserInteraction';
> -          break;
> -      }
>
> insert following case:
> case AutovalidateMode.onUnfocus:
> result = 'onUnfocus';
> break;
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/peiffer-innovations/json_theme/pull/212#pullrequestreview-2250551973>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AMQI2OKKEMO76E734RXOSTLZSR3TZAVCNFSM6AAAAABMWQRE3OVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDENJQGU2TCOJXGM>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-09-09 23:20 UTC, jpeiffer approved these changes

2024-09-09 23:20 UTC, jpeiffer commented
Thanks for the PR but this was already applied.

2024-09-09 23:20 UTC, closed without merging