Add Support to flutter 3.27
peiffer-innovations/json_theme pull request #229
Opened 2024-11-04 15:17 UTC by barbl058

## Description

Current flutter beta version (3.27) has some changes on ThemeData, this PR intends to adapt `json_theme` to use the new 
[TabBarThemeData instead of TabBarTheme](https://github.com/flutter/flutter/pull/156253), [CardThemeData instead of CardTheme](https://github.com/flutter/flutter/pull/153254) and [DialogThemeData instead of DialogTheme](https://github.com/flutter/flutter/pull/155129)

## Checklist

Before you create this PR confirm that it meets all requirements listed below by checking the relevant checkboxes (`[x]`). This will ensure a smooth and quick review process.

- [x] I read the [Code Style Guide] and followed the process outlined there for submitting PRs.
- [x] All existing and new tests are passing.
- [x] I updated/added relevant documentation (doc comments with `///`).
- [x] The analyzer (`flutter analyze` or `dart analyze`) does not report any problems on my PR.
- [x] I updated `pubspec.yaml` with an appropriate new version according to the [pub versioning philosophy].
- [x] I updated `CHANGELOG.md` to add a description of the change.
- [x] I am authorized to release this code under the MIT License and agree to do so

## UI Change

Does your PR affect any UI screens?

- [x] No, there are no UI impacts with this PR.

[Code Style Guide]: https://github.com/peiffer-innovations/documentation/blob/main/CODE_STYLE.md
[pub versioning philosophy]: https://www.dartlang.org/tools/pub/versioning

2024-11-04 22:06 UTC, jpeiffer requested changes
Thanks for this, always good to get ahead of things.  A few comments / suggestions.

2024-11-04 22:06 UTC, jpeiffer commented on json_theme/CHANGELOG.md
> +## [6.5.4] - UPDATE THIS
Let's use `7.0.0-dev.1` so we can merge and release it without breaking folks.

2024-11-04 22:06 UTC, jpeiffer commented on json_theme/pubspec.yaml
> +version: '6.5.4'
Let's use `7.0.0-dev.1` so we can merge and release it without breaking folks.

2024-11-04 22:06 UTC, jpeiffer commented on json_theme/lib/src/codec/theme_encoder.dart
> +  static Map<String, dynamic>? encodeTabBarTheme(TabBarThemeData? value) {
This should be named `encodeTabBarThemeData` since it now takes a `ThemeBarData`.

Also, curious why there isn't a matching ThemeDecoder change.

2024-11-04 22:06 UTC, jpeiffer commented on json_theme/lib/src/codec/theme_encoder.dart
> +  static Map<String, dynamic>? encodeDialogTheme(DialogThemeData? value) {
This should be named encodeDialogThemeData since it now takes a DialogThemeData.

Also, curious why there isn't a matching ThemeDecoder change.

2024-11-05 15:48 UTC, barbl058 commented
Comments solved, can you take a look again @jpeiffer?

2024-11-06 12:57 UTC, Gustl22 commented on json_theme/lib/src/codec/theme_encoder.dart
> -        'cardTheme': encodeCardTheme(value.cardTheme),
I think we could make in non breaking by adding a condition like this before:

```
      Object cardTheme = value.cardTheme;
      if (cardTheme is CardTheme) {
        cardTheme = cardTheme.data;
      } else if (cardTheme is! CardThemeData) {
        throw ArgumentError('cardTheme must be either a CardThemeData or a CardTheme');
      }
```

And then something like `encodeCardTheme(cardTheme as CardThemeData)`

Like done from flutter themselves: https://github.com/flutter/flutter/pull/155129/files#diff-9d9b537da8ee2b1c3d29615749e838767109e585bd59cdbd4ac356e30f344505R504

2024-11-11 16:17 UTC, Gustl22 commented on json_theme/lib/src/codec/theme_encoder.dart
> -        'cardTheme': encodeCardTheme(value.cardTheme),
@barbl058  would that be an option?

2024-11-12 13:57 UTC, Gustl22 commented on json_theme/lib/src/codec/theme_encoder.dart
> -        'cardTheme': encodeCardTheme(value.cardTheme),
Sorry, forget what I said, there's no way of handling this, as the classes I check don't even yet exist.

2024-11-12 14:06 UTC, Gustl22 commented on json_theme/pubspec.yaml
>    sdk: '>=3.2.0 <4.0.0'
```suggestion
  sdk: '>=3.2.0 <4.0.0'
  flutter: ">=3.27.0-0.1.pre"
```

2024-12-11 21:55 UTC, jesse-shaw-egeo commented
I think it's time!

2024-12-12 03:30 UTC, jpeiffer approved these changes

2024-12-12 03:34 UTC, merged

2024-12-12 03:34 UTC, jpeiffer commented
I'm a rebel!  I choose to merge!!!  😁

2024-12-12 03:52 UTC, Gustl22 commented
That's exciting. Shouldn't we also add a flutter min constraint (as I proposed before) so users who upgrade immediately know why their build is failing with older flutter versions?
https://github.com/peiffer-innovations/json_theme/pull/229#discussion_r1838163593